controller_joint_names: ['', 'link_1_joint', 'link_2_joint', 'link_3_joint', 'link_4_joint', 'link_5_joint', 'link_6_joint', 'left_finger_1_joint', 'left_finger_2_joint', 'right_finger_1_joint', 'right_finger_2', ]
